version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 7 * * *"
      timezone: "America/Denver"
    allow:
      - dependency-name: "Mythetech.*"
    groups:
      mythetech:
        patterns:
          - "Mythetech.*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
