<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" />
      <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="Protos/**/*.proto" ProtoRoot="Protos" GrpcServices="None" />
    </ItemGroup>

</Project>
