<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<None Remove="Assemblies\" />
		<None Remove="Assemblies\Endpoints\" />
		<None Remove="Assemblies\Models\" />
		<None Remove="Admin\" />
		<None Remove="Subscriptions\" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Assemblies\" />
		<Folder Include="Assemblies\Endpoints\" />
		<Folder Include="Admin\" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Iris.Contracts.Generators\Iris.Contracts.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>
</Project>