parameters:
  - name: enableSigning
    displayName: 'Enable signing'
    type: boolean
    default: false
  - name: buildWindows
    displayName: 'Build Windows'
    type: boolean
    default: true
  - name: buildMac
    displayName: 'Build macOS'
    type: boolean
    default: true
  - name: buildLinux
    displayName: 'Build Linux'
    type: boolean
    default: true

trigger: none

pr: none

variables:
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        strategy:
          matrix:
            windows:
              imageName: 'windows-latest'
              rid: 'win-x64'
              platform: 'Windows'
              icon: 'icon.ico'
              condition: eq('${{ parameters.buildWindows }}', true)
            mac:
              imageName: 'macOS-latest'
              rid: 'osx-x64'
              platform: 'macOS'
              icon: 'iris.icns'
              condition: eq('${{ parameters.buildMac }}', true)
            linux:
              imageName: 'ubuntu-latest'
              rid: 'linux-x64'
              platform: 'Linux'
              icon: 'icon.png'
              condition: eq('${{ parameters.buildLinux }}', true)
        pool:
          vmImage: $(imageName)
        condition: succeeded()
        steps:
          - checkout: self
            fetchDepth: 0
            displayName: 'Check-out Repo'

          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            displayName: 'Install Velopack CLI'
            inputs:
              command: 'custom'
              custom: 'tool'
              arguments: 'update -g vpk'
              
          - task: PowerShell@2
            displayName: 'Get Version'
            inputs:
              targetType: 'inline'
              script: |
                $buildNumber = "$(Build.BuildId)"
                Write-Host "##vso[task.setvariable variable=buildVersion]$buildNumber"
                
          - task: DotNetCoreCLI@2
            displayName: 'Publish $(platform)'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'Iris.Desktop/Iris.Desktop.csproj'
              arguments: '-c $(buildConfiguration) -r $(rid) --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=false -o $(Build.ArtifactStagingDirectory)/publish/$(platform)'
              zipAfterPublish: false

          - powershell: |
              Write-Host "Show all folder content ArtifactStagingDirectory"
              Get-ChildItem -Path $(Build.ArtifactStagingDirectory)\*.* -Recurse -Force
            errorActionPreference: continue
            displayName: 'PowerShell Script List folder structure'
            continueOnError: true

          - task: CmdLine@2
            displayName: 'Create Velopack Release for $(platform)'
            inputs:
              script: 'vpk pack -u "Iris.Desktop" -v "1.0.$(buildVersion)-preview" -o "$(Build.ArtifactStagingDirectory)/releases/$(platform)" -p "$(Build.ArtifactStagingDirectory)/publish/$(platform)/Iris.Desktop" --icon "Iris.Desktop/wwwroot/$(icon)"'
            
          - task: TrustedSigning@0
            displayName: 'Sign Velopack executables'
            condition: and(succeeded(), eq('${{ parameters.enableSigning }}', true))
            inputs:
              Endpoint: 'https://eus.codesigning.azure.net/'
              TrustedSigningAccountName: 'signing-mt-global'
              FileDigest: 'SHA256'
              FilesToSign: '$(Build.ArtifactStagingDirectory)/releases/$(platform)/*.exe'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish $(platform) Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/releases/$(platform)'
              artifact: 'iris-$(platform)-$(buildVersion)'
              publishLocation: 'pipeline'

  - stage: Publish
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: UploadToStorage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Artifacts'
            inputs:
              path: '$(Pipeline.Workspace)/releases'
              
          - task: AzureCLI@2
            displayName: 'Upload executables to Azure Blob Storage'
            inputs:
              azureSubscription: 'mythetech-iris-dev(0a5006b3-277f-40e2-abaa-a5678ab2a5d5)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                if [[ ${{ parameters.buildWindows }} == true ]]; then
                  az storage blob upload-batch --account-name stgmtirisdev --destination release --source "$(Pipeline.Workspace)/releases/iris-Windows-*" --overwrite
                fi
                if [[ ${{ parameters.buildMac }} == true ]]; then
                  az storage blob upload-batch --account-name stgmtirisdev --destination release --source "$(Pipeline.Workspace)/releases/iris-macOS-*" --overwrite
                fi
                if [[ ${{ parameters.buildLinux }} == true ]]; then
                  az storage blob upload-batch --account-name stgmtirisdev --destination release --source "$(Pipeline.Workspace)/releases/iris-Linux-*" --overwrite
                fi